spring.application.name=SpringAICode
# Ollama connection
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=mistral:latest
spring.ai.ollama.chat.options.temperature=0.7
# Embeddings
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.options.model=bge-large
# PGVector
spring.datasource.url=jdbc:postgresql://localhost:5432/koushik
spring.datasource.username=postgres
spring.datasource.password=2403
spring.datasource.driver-class-name=org.postgresql.Driver
# IMPORTANT: Let schema.sql own the schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# Run schema.sql
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:init/schema.sql
# Allow bean definition overriding for development purposes
spring.main.allow-bean-definition-overriding=true